#pragma once
#ifdef ARGLESS_CORE_HPP

#undef _ARGLESS_BEGIN
#undef _ARGLESS_END
#undef _ARGLESS

#undef _ARGLESS_PRIVATE_BEGIN
#undef _ARGLESS_PRIVATE_END
#undef _ARGLESS_PRIVATE

#undef _ARGLESS_STATIC_ASSERT
#undef _ARGLESS_ASSERT

#undef _ARGLESS_CONVERT_CHAR
#undef _ARGLESS_CHAR
#undef _ARGLESS_CONVERT_TEXT
#undef _ARGLESS_TEXT

#undef _ARGLESS_HAS_CPP11
#undef _ARGLESS_HAS_CPP14
#undef _ARGLESS_HAS_CPP17
#undef _ARGLESS_HAS_CPP20

#undef _ARGLESS_HAS_CHAR8_T

// defined in other headers

#undef _ARGLESS_PARSERS

#endif
